from sqlalchemy import Column, Integer, String, Text, DateTime, JSON
from sqlalchemy.orm import declarative_base
from pgvector.sqlalchemy import Vector
from datetime import datetime
from zoneinfo import ZoneInfo

Base = declarative_base()

class DocumentChunk(Base):
    """
    SQLAlchemy model representing the 'document_chunks' table in the Supabase database.
    This table stores the smaller text chunks extracted from uploaded PDFs, along with 
    their mathematical vector embeddings generated by Hugging Face.
    """
    __tablename__ = "document_chunks"

    # Unique identifier for each chunk
    id = Column(Integer, primary_key=True, index=True)
    
    # The name of the original file (e.g., 'World Bank Report 2025.pdf')
    source = Column(String, index=True, nullable=False) 
    
    # The specific page number the chunk was extracted from
    page_number = Column(Integer, nullable=True)
    
    # The order of the chunk in the document (e.g., chunk 1, chunk 2)
    chunk_index = Column(Integer, nullable=False)
    
    # The actual text content extracted by the unstructured library
    text_content = Column(Text, nullable=False)
    
    # A JSON field to store any extra metadata (like bounding box coordinates or table structure)
    metadata_json = Column(JSON, nullable=True) 
    
    # The pgvector column that stores the numerical embedding.
    # The Hugging Face model 'BAAI/bge-m3' outputs 1024-dimensional vectors.
    embedding = Column(Vector(1024)) 
    
    # Timestamp of when the chunk was saved to the database (in IST)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(ZoneInfo("Asia/Kolkata")))
