import enum
from sqlalchemy import Column, Integer, String, Text, DateTime, JSON, ForeignKey, UniqueConstraint, Enum
from sqlalchemy.orm import declarative_base
from pgvector.sqlalchemy import Vector
from datetime import datetime
from zoneinfo import ZoneInfo

Base = declarative_base()

class DocumentStatus(str, enum.Enum):
    NEW = "NEW"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class Document(Base):
    """
    SQLAlchemy model representing the 'documents' table.
    Tracks files by their SHA-256 hash to ensure idempotency.
    """
    __tablename__ = "documents"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    filename = Column(String, nullable=False)
    file_hash = Column(String, unique=True, index=True, nullable=False)
    config_hash = Column(String, nullable=False)
    status = Column(Enum(DocumentStatus), default=DocumentStatus.NEW, nullable=False)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(ZoneInfo("Asia/Kolkata")))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(ZoneInfo("Asia/Kolkata")), onupdate=lambda: datetime.now(ZoneInfo("Asia/Kolkata")))
    completed_at = Column(DateTime(timezone=True), nullable=True)
    file_path = Column(String, nullable=True)

class DocumentChunk(Base):
    """
    SQLAlchemy model representing the 'document_chunks' table in the Supabase database.
    This table stores the smaller text chunks extracted from uploaded PDFs, along with 
    their mathematical vector embeddings generated by Hugging Face.
    """
    __tablename__ = "document_chunks"

    # Unique identifier for each chunk
    id = Column(Integer, primary_key=True, index=True)
    
    # Foreign key to the parent document
    document_id = Column(Integer, ForeignKey("documents.id"), nullable=False, index=True)
    
    # The specific page number the chunk was extracted from
    page_number = Column(Integer, nullable=True)
    
    # The order of the chunk in the document (e.g., chunk 1, chunk 2)
    chunk_index = Column(Integer, nullable=False)
    
    # The actual text content extracted by the unstructured library
    text_content = Column(Text, nullable=False)
    
    # A JSON field to store any extra metadata (like bounding box coordinates or table structure)
    metadata_json = Column(JSON, nullable=True) 
    
    # The pgvector column that stores the numerical embedding.
    # The Hugging Face model 'BAAI/bge-m3' outputs 1024-dimensional vectors.
    embedding = Column(Vector(1024)) 
    
    # Timestamp of when the chunk was saved to the database (in IST)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(ZoneInfo("Asia/Kolkata")))

    __table_args__ = (
        UniqueConstraint('document_id', 'chunk_index', name='uix_doc_chunk_index'),
    )
